wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    code_path: code/Experiment-8/train.py
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1656516678
    t:
      1:
      - 1
      - 5
      - 11
      - 40
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 40
      - 49
      - 53
      - 55
      3:
      - 16
      4: 3.10.4
      5: 0.12.19
      6: 4.18.0
      8:
      - 3
      - 5
embedding_length:
  desc: null
  value: 128
final-batch_size:
  desc: null
  value: 4
final-epochs:
  desc: null
  value: 10
hidden_size:
  desc: null
  value: 512
lr:
  desc: null
  value: 0.0001
name:
  desc: null
  value: pre-train
pre-batch_size:
  desc: null
  value: 64
pre-epochs:
  desc: null
  value: 1
r2_coeff:
  desc: null
  value: 0.0007
stdev_coeff:
  desc: null
  value: 0.8
stdev_start:
  desc: null
  value: 0.1
stdev_start_coeff:
  desc: null
  value: 1.0
