wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    code_path: code/Experiment-3/pre-train-aes.py
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1654167567
    t:
      1:
      - 1
      - 5
      - 11
      - 40
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 40
      - 49
      - 53
      - 55
      3:
      - 13
      4: 3.7.12
      5: 0.12.17
      6: 4.19.2
      8:
      - 5
